# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Cmake/3.8.1/Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Cmake/3.8.1/Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /afs/atlass01.physik.uni-bonn.de/user/mbertemes/Documents/belle/BasicFit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /afs/atlass01.physik.uni-bonn.de/user/mbertemes/Documents/belle/BasicFit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Cmake/3.8.1/Linux-x86_64/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Cmake/3.8.1/Linux-x86_64/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /afs/atlass01.physik.uni-bonn.de/user/mbertemes/Documents/belle/BasicFit/CMakeFiles /afs/atlass01.physik.uni-bonn.de/user/mbertemes/Documents/belle/BasicFit/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /afs/atlass01.physik.uni-bonn.de/user/mbertemes/Documents/belle/BasicFit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BasicFit

# Build rule for target.
BasicFit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BasicFit
.PHONY : BasicFit

# fast build rule for target.
BasicFit/fast:
	$(MAKE) -f CMakeFiles/BasicFit.dir/build.make CMakeFiles/BasicFit.dir/build
.PHONY : BasicFit/fast

src/FitterClass.o: src/FitterClass.cc.o

.PHONY : src/FitterClass.o

# target to build an object file
src/FitterClass.cc.o:
	$(MAKE) -f CMakeFiles/BasicFit.dir/build.make CMakeFiles/BasicFit.dir/src/FitterClass.cc.o
.PHONY : src/FitterClass.cc.o

src/FitterClass.i: src/FitterClass.cc.i

.PHONY : src/FitterClass.i

# target to preprocess a source file
src/FitterClass.cc.i:
	$(MAKE) -f CMakeFiles/BasicFit.dir/build.make CMakeFiles/BasicFit.dir/src/FitterClass.cc.i
.PHONY : src/FitterClass.cc.i

src/FitterClass.s: src/FitterClass.cc.s

.PHONY : src/FitterClass.s

# target to generate assembly for a file
src/FitterClass.cc.s:
	$(MAKE) -f CMakeFiles/BasicFit.dir/build.make CMakeFiles/BasicFit.dir/src/FitterClass.cc.s
.PHONY : src/FitterClass.cc.s

src/FitterInputClass.o: src/FitterInputClass.cc.o

.PHONY : src/FitterInputClass.o

# target to build an object file
src/FitterInputClass.cc.o:
	$(MAKE) -f CMakeFiles/BasicFit.dir/build.make CMakeFiles/BasicFit.dir/src/FitterInputClass.cc.o
.PHONY : src/FitterInputClass.cc.o

src/FitterInputClass.i: src/FitterInputClass.cc.i

.PHONY : src/FitterInputClass.i

# target to preprocess a source file
src/FitterInputClass.cc.i:
	$(MAKE) -f CMakeFiles/BasicFit.dir/build.make CMakeFiles/BasicFit.dir/src/FitterInputClass.cc.i
.PHONY : src/FitterInputClass.cc.i

src/FitterInputClass.s: src/FitterInputClass.cc.s

.PHONY : src/FitterInputClass.s

# target to generate assembly for a file
src/FitterInputClass.cc.s:
	$(MAKE) -f CMakeFiles/BasicFit.dir/build.make CMakeFiles/BasicFit.dir/src/FitterInputClass.cc.s
.PHONY : src/FitterInputClass.cc.s

utils/Utils.o: utils/Utils.cc.o

.PHONY : utils/Utils.o

# target to build an object file
utils/Utils.cc.o:
	$(MAKE) -f CMakeFiles/BasicFit.dir/build.make CMakeFiles/BasicFit.dir/utils/Utils.cc.o
.PHONY : utils/Utils.cc.o

utils/Utils.i: utils/Utils.cc.i

.PHONY : utils/Utils.i

# target to preprocess a source file
utils/Utils.cc.i:
	$(MAKE) -f CMakeFiles/BasicFit.dir/build.make CMakeFiles/BasicFit.dir/utils/Utils.cc.i
.PHONY : utils/Utils.cc.i

utils/Utils.s: utils/Utils.cc.s

.PHONY : utils/Utils.s

# target to generate assembly for a file
utils/Utils.cc.s:
	$(MAKE) -f CMakeFiles/BasicFit.dir/build.make CMakeFiles/BasicFit.dir/utils/Utils.cc.s
.PHONY : utils/Utils.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BasicFit"
	@echo "... src/FitterClass.o"
	@echo "... src/FitterClass.i"
	@echo "... src/FitterClass.s"
	@echo "... src/FitterInputClass.o"
	@echo "... src/FitterInputClass.i"
	@echo "... src/FitterInputClass.s"
	@echo "... utils/Utils.o"
	@echo "... utils/Utils.i"
	@echo "... utils/Utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

